---
driver_plugin: joyent
driver_config:
  require_chef_omnibus: 12.6.0
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  joyent_version: ~8.0
  joyent_image_id: 5cdc6dde-d6ad-11e5-8b11-8337e6f86725
  joyent_flavor_id: g4-general-4G

provisioner: chef_zero

transport:
  ssh_key: <%= ENV['SDC_CLI_IDENTITY'] %>
  username: root

platforms:
- name: ubuntu-14.04
  driver:

suites:
  - name: master
    run_list:
      - recipe[apt]
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
      consul:
        bind_addr: '127.0.0.1'
        client_addr: '127.0.0.1'
      optoro_consul:
        register_consul_service: true
        server: false
        service:
          name: redis
          tags:
            - master
          port: 6379
          checks:
            - { script: '/usr/local/bin/redis-cli PING', interval: '10s' }

  - name: master-3.2
    run_list:
      - recipe[apt]
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
        version: 3.2.1
      consul:
        bind_addr: '127.0.0.1'
        client_addr: '127.0.0.1'
      optoro_consul:
        register_consul_service: true
        server: false
        service:
          name: optoro-redis
          tags:
            - master
          port: 6379
          checks:
            - { script: '/usr/local/bin/redis-cli PING', interval: '10s' }

  - name: replication-client
    run_list:
      - recipe[apt]
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
          - port: 6380
            slaveof:
              address: 127.0.0.1
              port: 6379
