---
driver_plugin: joyent
driver_config:
  vm_hostname: base
  joyent_username: <%= ENV['SDC_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_KEY_FILE'] %>
  joyent_keyname: <%= ENV['SDC_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_URL'] %>
  require_chef_omnibus: '12.6.0'
  joyent_networks:
   - c0bf4505-75ca-41ea-a706-a8ca34a84f54
  joyent_image_id: a3c7b9ba-279d-11e6-aecd-07e1aa0cc545
  joyent_flavor_id: g4-general-4G
  joyent_version: '~7.0'
provisioner: chef_zero

platforms:
- name: ubuntu-14.04
  driver:

suites:
  - name: master
    run_list:
      - recipe[apt]
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
      consul:
        bind_addr: '127.0.0.1'
        client_addr: '127.0.0.1'
      optoro_consul:
        register_consul_service: true
        server: false
        service:
          name: redis
          tags:
            - master
          port: 6379
          checks:
            - { script: '/usr/local/bin/redis-cli PING', interval: '10s' }

  - name: master-3.2
    run_list:
      - recipe[apt]
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
        version: 3.2.1
      consul:
        bind_addr: '127.0.0.1'
        client_addr: '127.0.0.1'
      optoro_consul:
        register_consul_service: true
        server: false
        service:
          name: optoro-redis
          tags:
            - master
          port: 6379
          checks:
            - { script: '/usr/local/bin/redis-cli PING', interval: '10s' }

  - name: replication-client
    run_list:
      - recipe[apt]
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
          - port: 6380
            slaveof:
              address: 127.0.0.1
              port: 6379
