name 'optoro_redis'
maintainer 'Optoro'
maintainer_email 'devops@optoro.com'
license 'MIT'
description 'Installs/Configures redis servers'
long_description 'Installs/Configures redis servers'
version '0.1.3'

depends 'redisio', '~> 2.2.4'
depends 'optoro_monit'
