name 'optoro_redis'
maintainer 'Optoro'
maintainer_email 'devops@optoro.com'
license 'MIT'
description 'Installs/Configures redis servers'
long_description 'Installs/Configures redis servers'
issues_url 'https://github.com/optoro-devops/optoro_redis'
source_url 'https://github.com/optoro-devops/optoro_redis'
version '0.1.17'

depends 'redisio', '~> 2.4.2'
depends 'optoro_consul'
depends 'aws'
